version: "3.9"

services:
  postgres:
    container_name: shop_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop
    volumes:
      - ./pgdata:/var/lib/postgresql/data
